version: "3.8"
services:
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
  frontend:
    build: frontend
    command: yarn dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/app
