# Generated by Django 4.2 on 2023-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('sports_and_outdoors', 'Sports and Outdoors'), ('health_and_wellness', 'Health and Wellness'), ('toys_and_games', 'Toys and Games'), ('food_and_beverage', 'Food and Beverage')], max_length=30)),
            ],
        ),
    ]
